deploy_dev:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - whoami
  script:
    - cd /var/www/html/dev/app
    - pwd
    - git status
    - git fetch
    - git checkout develop
    - git status
    - git pull origin develop
    - yarn
    - yarn build
  only:
    - develop

deploy_staging:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - whoami
  script:
    - cd /var/www/html/staging/app
    - pwd
    - git status
    - git fetch
    - git checkout develop
    - git status
    - git pull origin develop
    - yarn
    - yarn build
  only:
    - staging

