const comapyInverter = [
  {
    amountElectricDay: 5768,
    amountElectricMonth: 5768,
    comId: 1,
    comName: '아반시스 코리아 Avansys Korea',
    cumulativeElectric: 71147,
    electricRealtime: 0,
    event: 0,
    id: 1,
    name: 'MOD-P5C1T0',
    posId: 5,
    posName: '본관 남측 phía nam tòa nhà chính ',
    ratePower: 91,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 1,
    comName: '아반시스 코리아 Avansys Korea',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 2,
    name: 'MOD-P6C1T0',
    posId: 6,
    posName: '본관 동측 phía đông tòa nhà chính',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 1,
    comName: '아반시스 코리아 Avansys Korea',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 3,
    name: 'MOD-P10C2T0',
    posId: 10,
    posName: '발전동 서측 phía tây trạm phát điện',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 2,
    comName: '에스지에너지 SG Energy',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 4,
    name: 'MOD-P12C2T0',
    posId: 12,
    posName: '방음벽 tường cách âm',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 2,
    comName: '에스지에너지 SG Energy',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 5,
    name: 'MOD-P6C3T0',
    posId: 6,
    posName: '본관 동측 phía đông tòa nhà chính',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 2,
    comName: '에스지에너지 SG Energy',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 1,
    id: 6,
    name: 'MOD-P5C4T0',
    posId: 5,
    posName: '본관 남측 phía nam tòa nhà chính ',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 5,
    comName: '중앙강재 / 옥토끼이미징 Central Steel / Jade Rabbit Imaging',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 7,
    name: 'MOD-P4C5T0',
    posId: 4,
    posName: '경비실 입면 mặt chính phòng bảo vệ',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 5,
    comName: '중앙강재 / 옥토끼이미징 Central Steel / Jade Rabbit Imaging',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 8,
    name: 'MOD-P10C5T0',
    posId: 10,
    posName: '발전동 서측 phía tây trạm phát điện',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 6,
    comName: '중앙강재 Central steel',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 9,
    name: 'MOD-P8C6T0',
    posId: 8,
    posName: '별관 지붕 mái nhà tòa nhà phụ',
    ratePower: 0,
  },
  {
    amountElectricDay: 0,
    amountElectricMonth: 0,
    comId: 7,
    comName: '에스케이솔라에너지 SK Solar Energy',
    cumulativeElectric: 0,
    electricRealtime: 0,
    event: 0,
    id: 10,
    name: 'MOD-P7C7T0',
    posId: 7,
    posName: '본관 옥탑 tầng thượng tòa nhà chính',
    ratePower: 0,
  },
];

export default comapyInverter;
