const ROUTERS = {
  ROOT: '/',
  LOGIN: '/login',
  DEVICE: '/device',
  STORES: '/stores',
  STORES_DETAIL: '/stores/:id',
  DEVICE_DETAIL: '/device/:id',
  REVENUE_TIME: '/revenues/revenue-time',
  MEMBER: '/members',
  REVENUEDAY_DAY: '/revenues/revenue-day',
  MEMBER_DETAIL: '/members/:phone',
  REVENUE_PRODUCT: '/revenues/product',
  REVENUE_STORE: '/revenues/store',
  PAYMENT: '/revenues/payment',
  INVENTORY: '/inventory',
  INVENTORY_DETAIL: '/inventory/:id',
  MERCHANDISE: '/merchandise',
  MERCHANDISE_ADD: '/merchandise/add',
  REGISTER_SELF_PRODUCT: '/merchandise/registerProduct',
  SEFT_PRODUCT: '/merchandise/manual',
  SELF_PRODUCT: '/merchandise/manual/:id',
  MERCHANDISE_DETAIL: '/merchandise/:id',
  STATUS_MERCHANDISE: '/merchandise/status',
  ADVERTING: '/adverting',
  REGISTER_PRODUCT: '/merchandise/add',
  EDIT_PRODUCT: '/merchandise/edit',
  PICKUP_ORDER: '/management/pickup-order',
  PICKUP_ORDER_DETAIL: '/management/pickup-order/:id',
  QA: '/management/qa',
  QA_DETAIL: '/management/qa/:id',
  NOTICE: '/management/notice',
  NOTICE_DETAIL: '/management/notice/:id',
  NOTICE_REGISTER: '/management/notice/add',
  EVENT_APP: '/management/event-app',
  EVENT_ADD_APP: '/management/event-app/add',
  EVENT_DETAIL_APP: '/management/event-app/:id',
};

export default ROUTERS;
