const ROUTERS = {
  MAIN_PAGE: `/`,
  LOGIN: `/login`,
  SIGN_UP: '/sign-up',
  FIND_PASSWORD: '/find-password',
  MY_POINT: '/my-point',
  EVENT: '/event',
  EVENT_DETAIL: `/event/:id`,
  RECOMMENDED_USER: '/recommended-user',
  TODAY_WORD: '/today-word',
  HOT_STAR: '/recently-hot-star',
  POPULAR_DAY: '/popular-day',
  POPULAR_WEEKLY: '/popular-weekly',
  SEARCH: '/search',
  SEARCH_CATEGORY: '/search/:category',
  VIDEO_PROFILE: '/video-profile',
  VIDEO_PROFILE_CATEGORY: '/video-profile/:id',
  RECOMMENDED_PAGE: '/recommended',
  SPECIFIC_FEELING: '/specificFeeling',
  SPECIFIC_FEELING_DETAIL: '/specificFeeling/:category',
  TODAY_WORD_DETAIL: '/today-word/:id',
  FAVORITE: '/favorite',
  MY_PAGE: '/my-page',
  MY_INFORMATION: '/my-information',
  MY_INFORMATION_SNS: '/my-information-sns',
  PAYMENT: '/payment',
  NOTICE: '/notice',
  PUSH: '/push',
  MAKINGINQUIRY: '/making-inquiry',
  SETTING_LANGUAGE: '/setting-language',
  TERMS_CONDITIONS: '/condition',
  SETTING_INFO: `/setting-info`,
  MEMBER_SHIP: '/login/success',
  NON_MEMBER: '/non-member',
  EDIT_SETTING_INFO: `/setting-info/edit`,
  POPUP_MAIL: `/popup-mail/:language`,
};

export default ROUTERS;
