/* eslint-disable global-require */

const IMAGES = {
  iconGraph: require('assets/images/icon_graph.png'),
  icon_close: require('assets/images/icon_closed.svg'),
  mockUp: require('assets/images/m_icon_02.png'),
  icon_radio_on: require('assets/images/icon_radio_on.svg'),
  icon_next: require('assets/images/icon_arrow_list_r.svg'),
  icon_power: require('assets/images/icon_label/icon-power.png'),
  icon_temperature: require('assets/images/icon_label/icon-temperature.png'),
  icon_insolation: require('assets/images/icon_label/icon-insolation.png'),
  icon_event: require('assets/images/icon-event.png'),
  icon_search: require('assets/images/icon-search.png'),
  setup: require('assets/images/setup.png'),
  iconTitle: require('assets/images/icon_title.png'),
  icon_title: require('assets/images/icon_main/icon_title.png'),
  icon_day: require('assets/images/icon_main/icon_day.png'),
  icon_month: require('assets/images/icon_main/icon_month.png'),
  icon_year: require('assets/images/icon_main/icon_year.png'),
  icon_plus: require('assets/images/icon_main/icon_plus.png'),
  icon_location: require('assets/images/icon_main/icon_location.png'),
  icon_location_on: require('assets/images/icon_main/icon_location_on.png'),
  icon_title_header: require('assets/images/title_icon.png'),
  icon_arrow: require('assets/images/icon_arrow.png'),
  icon_event_card: require('assets/images/icon_event_card.png'),
  iconSubtitle: require('assets/images/icon_subtitle.png'),
  angle1: require('assets/images/angle1.svg'),
  angle2: require('assets/images/angle2.svg'),
  angle3: require('assets/images/angle3.svg'),
  angle4: require('assets/images/angle4.svg'),
  iconCalendar: require('assets/images/icon_calander.png'),
  ico_event2: require('assets/images/ico-event2.svg'),
  arrow_right: require('assets/images/arrow_right.svg'),
  icon_day_large: require('assets/images/icon_day_large.svg'),
  icon_month_large: require('assets/images/icon_month_large.svg'),
  icon_year_large: require('assets/images/icon_year_large.svg'),
  icon_plus_large: require('assets/images/icon_plus_large.svg'),
  btn_logout: require('assets/images/btn_logout.svg'),
  default_logo: require('assets/images/logo_company/logo_l&c@3x.png'),
  motion_weather_blue: require('assets/images/motion/icon_weather_blue.gif'),
  motion_weather_orange: require('assets/images/motion/icon_weather_orange.gif'),
};

export default IMAGES;
